---
title: "CRIM 515 Exercise 1 Template"
author: "My Name"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
calls <- read.csv(sprintf("https://docs.google.com/uc?id=%s&export=download", 
                          "1wKXnsCgcEuipeU9Xv3xBUBAA-B2wprtq"))
```

# Graph 1
```{r, echo=FALSE, message=FALSE, warning=FALSE}
calls %>% filter(hour != "NA") %>%
  ggplot() +
  geom_line(aes(x = as.factor(hour)), stat = "count", group = 1, color = "blue", size = 1) +
  labs(title = "Calls by Hour Reported \n2007 - 2024", x = "Hour Reported", y = "Number of Calls (Thousands)") +
  theme(plot.title = element_text(hjust = 0.5, size = 14),
        axis.text.x = element_text(color = "black", size = 10),
        axis.text.y = element_text(color = "black", size = 10),
        axis.ticks.y = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "gray"),
        panel.background = element_blank()) +
  scale_y_continuous(limits = c(0, 25000), breaks = c(0, 5000,10000,15000,20000,25000), labels = c(0,5,10,15,20,25))
```

# Graph 2
```{r}

```

