---
title: "CRIM 515 Project 1 Template"
author: "My Name"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  cleanrmd::html_document_clean:
    theme: water-dark
    toc: yes
---

Each research project will follow the general flow outlined below. Use this format as much or as little as you'd like, as long as the required components are covered.

# 1. Research Question

### INSTRUCTIONS

The goal of this project is to scientifically assess a complex criminal justice topic. You are taking a broad topic and refining it to a *measurable*, *answerable* question.

Your research question should consider **behavior**, **space**, and **time**. You'll either *measure* or *control* for each of these. 

- Behavior: what
- Space: where
- Time: when

Additionally, you'll need to consider *how* you define and measure change.

### EXAMPLE
***What is the interaction between firearm events and firearm access?***

# 2. Literature Review

### INSTRUCTIONS

Identify one source that is relevant and related to your research question. This source needs to be an article from a peer-academic academic journal. Briefly describe the source and why it’s relevant to your study in approximately one paragraph. Include information about the **research question**, **data**, **methods**, and **findings**. 

# 3. Data

### INSTRUCTIONS

**Identifying** and **acquiring** relevant sources is something directly related to your research question, and we will develop in-class. It's worth noting your don't necessarily identify the question *before* the data. This section will be updated accordingly...

### SOURCES

#### Firearm Events
1. [FBI UCR SHR](https://cde.ucr.cjis.gov/LATEST/webapp/#/pages/explorer/crime/shr)

    - You want the Expanded Homicide Data
    - Do separate downloads for unique time periods and/or areas (states)
    - Time period downloads would allow you to compare homicides committed with a firearm over time, *controlling for location*
    - Area downloads would allow you to compare homicidies committed with a firearm across states, *controlling for time*
    - Use the page filters to adjust states and years
    - Download the 'Murder Victim by Weapon' table
    - **End Result:** results in multiple downloads: either multiple years of data, or multiple states of data

2. [Gun Violence Archive](https://www.gunviolencearchive.org/)

    - Select a type of event from the table at the bottom left of the homepage
    - Export as CSV that year's data
    - Go to Past Years section
    - Repeat the process for as many years as you want
    - **End result:** multiple yearly CSVs of event data

3. [Mother Jones](https://www.motherjones.com/politics/2012/12/mass-shootings-mother-jones-full-data/)

    - Just click and download
    - **End result:** one file

4. [The Violence Project](https://www.theviolenceproject.org/mass-shooter-database/)

    - One click download
    - **End result:** one file

#### Firearm Access
1. Seizures

    - Option 1, domestic: [DHS Customs & Border Protection](https://www.cbp.gov/document/stats/weapons-and-ammunition-seizures)
        - Get the most recently published data from the bottom of the page
        - **End result:** one file that needs filtering
    - Option 2, global: [United Nations](https://dataunodc.un.org/dp-firearms-arms-seized)
        - Click download dataset on the right
        - **End result:** one file

2. Laws

    - Option 1: [Everytown](https://everytownresearch.org/rankings/)
        - Option A: Manually convert the state rankings into a table
        - Option B: Explore by State - pick select states of interest, Compare, and manually convert data into a table
        - Option C: Explore by Policy - pick select policies, manually convert data into a table
        - ***Use Everytown if you are doing a state-by-state comparison of FBI UCR SHR***

    - Option 2: [RAND](https://www.rand.org/research/gun-policy/law-navigator.html)
        - Pick a law type, a weapon type, and a year, and then manually count states
        - ***Use RAND if you are doing a year-by-year comparison***
    
    - Option 3: [State Firearm Laws Database](http://www.statefirearmlaws.org/)
        - This site may be dead.

3. Suicides

    - Data from [CDC WONDER](https://wonder.cdc.gov/mcd.html)

First, you may just want to analyze firearm suicides.
Second, you may want to use the percentage of suicides committed with a firearm as a proxy for firearm ownership

Select any of the location/demographic paramters
Then in Underlying Cause of Death
For #6 choose all suicides
For #7 choose suicides by firearm
Export

4. Sales

FBI NICS
https://www.fbi.gov/file-repository/nics_firearm_checks_-_month_year.pdf

https://www.thetrace.org/2020/08/gun-sales-estimates/
Download the CSV

5. Traces
ATF Trace data
https://jasher.substack.com/p/atfs-2022-firearms-trace-data-is

# 4. Methods

### INSTRUCTIONS

**Building** a relevant methodology is largely dependent on your research question and data. Any good methodology involves multiple steps for acquiring, wrangling, cleaning, analyzing, and visualizing data. There is no single right answer here; rather, it’s the ability to craft a unique, distinct workflow that results in innovative work. 

This section will be updated accordingly during class and include these steps...

##### Acquire

##### Wrangle

##### Calculate

##### Visualize

Ultimately, your methodology will result in analysis that becomes findings. Some things to consider:

- What are the trends? 
- What happens the most, what happens the least?
- Are there anomalies? 
- What do the statistics tell you? 

# 5. Findings

### INSTRUCTIONS

So, that workflow and methodology you created? Use it to answer your research question. Based on the data acquired and the methods applied, what is your answer to the question? How confident are you in the results? What else? Is anything missing? Is the data complete? Is it accurate? Make sure to caveat your findings as necessary. Related, this section should be written in clear, concise, plain English statements. The methodology is for complex thought and processes; the findings are for easily digestible content.

# 6. So What

### INSTRUCTIONS

In the context of operating in a real criminal justice organization, how do your findings ***inform*** decision-making processes? Does what you’ve discovered ***confirm/deny*** conventional wisdom? How does a criminal justice organization ***operationalize*** these findings? Why do your findings matter, and what does a successful ***integration*** of your work look like? Be bold, and be specific. For example, check out [this](https://www.start.umd.edu/pubs/UIC_MPAC_START_SafeSpaces_CommunityBasedOrganizations_June2019.pdf), [this](https://start.umd.edu/pubs/UIC_MPAC_START_SafeSpaces_PublicHealthFramework_June2019.pdf), and [this](https://cebcp.org/evidence-based-policing/what-works-in-policing/research-evidence-review/focused-deterrence/). Sure, they are violent extremism, but the way they were built can be really useful in this context, too.  

As an example, specific to this project, [consider something like this](https://www.thetrace.org/2024/03/new-york-mass-shooting-victims-survivors/).

# Writing Tips

Related, some general notes about writing. Welcome to grad school, where the quality of your writing is held to a higher standard. Write directly. Thus, avoid using these words and phrases:

* Simply. Very. Indeed. Specifically. Perhaps. Arguably. Usually. Essentially. Could possibly. Could potentially. Necessarily. Only. Especially. In order to. Likely. Primarily. Generally. It is important that. It is essential to note.

Also, words have meanings. [Some are stronger than others](https://www.themuse.com/advice/185-powerful-verbs-that-will-make-your-resume-awesome). [Others aren’t real](https://www.rd.com/article/words-that-arent-words/).

Further, here’s some other strategies to consider:

* Read sentences aloud… but don’t write like you speak.
* Ask yourself - does this sentence make sense, by itself.
* It’s ok to occasionally use quotes, don’t copy specific language or words.
* If you don’t know the meaning of a word, don’t use it!

And finally, [this is just fun](https://www.thisworddoesnotexist.com/).

# Other Information/Reminders

1. When submitting your projects, you are submitting either an **HTML** or **PDF** output of your Markdown file, as an upload to Canvas - not via email.
2. When you are ready to see what the output looks like, **click the 'Knit' button.** The output file will be saved to the same folder this script is saved to.
3. *Never ever ever include any install.packages functions.* Either comment them out with a #, or delete them.

# Grading: 30pts

#### 1. Research Question
***2pts***

Provide a brief paragraph on the research question. State the question, in terms of behavior, space, and time. Define key terms and concepts, to include how variables will be measured.

#### 2. Literature Review
***2pts***

Provide a brief paragraph describing a prior study related to your current project. This study should be from a peer-academic academic journal. Include details about the *research question*, *data*, *methods*, and *findings*. Cite the article in *APA format*. 

#### 3. Data 
***2pts***

Provide a brief paragraph on the data used in this study. This includes the specific source(s), and the specific temporal and spatial constraints. Address any major advantages and disadvantages with using these data compared to other sources. Be specific enough that a reader could replicate this work.

#### 4. Methods
***2pts***

Provide a brief paragraph on the research methods leveraged to answer this question. This includes the software, calculations, skills, techniques, and unique workflows used to analyze your data and develop an answer. You do NOT need to describe click-by-click instructions or lines of code describing how you did things; you DO need to describe a logical process that is specific enough that a reader could replicate. 

#### 5. Findings
***10pts***

Provide at least five paragraphs on the findings of your study (*2pts each*). Your findings should be descriptive, clear, and comprehensively answer the original question. Each paragraph should describe a unique analytic insight dervied from your research. Each analytic insight should be the product of your methods, applied to your data, to provide part of an answer to your research question.

Address any limitations or factors to consider for future research. Make sure to actually answer the question! 

#### 6. So What
***5pts***

Provide a brief paragraph on the importance of this study, as a criminal justice professional. How can these findings be integrated into a real world environment? Be as specific as possible as to why your findings matter, and what a successful application of your work would look like. Include any potentially actionable or tangible conclusions (*4pts*). 

Based on your findings, include a brief discussion (2-3 sentences) on implications and opportunities for further research (*1pt*).

#### 7. Visuals
***6pts***

Provide at least three visuals of your data. These visuals should be relevant to your research and used as aids to articulate your findings. Think of these as support/evidence for your words. These visuals can be any combination of charts, tables, graphs, maps, or other similar graphics. All visuals should be intuitive and logical, meaning the reader can understand them without an additional explanation. 

- Thoughtful and logical: do they make sense to someone that has never seen them before? (*2pts*)
- All visuals should be somehow, someway referenced in the text (*2pts*) 
- Analytically meaningful: does each visual provide useful, relevant, and actionable insights? (*2pts*) 

#### 8. Formatting
***1pt***

- Error-free writing (*1pt*). No typos, run-on sentences, or sentence fragments. Proper punctuation. Real words. Need help paraphrasing dense content? [Try this](https://quillbot.com/). And [here’s a great reference](https://cognella-titles-sneakpreviews.s3-us-west-2.amazonaws.com/83869-1A-URT/83869-1A_SP.pdf), too.
- File submitted as the knitted HTML output of an RMarkdown file, via Canvas (*1pt*).

ONE LAST THING... the source code for creating this file can be [found here](https://github.com/matthew-danna/criminal-justice-research-methods-data-analysis/blob/main/scripts/2024%20fall/CRIM%20515%20Project%20Template.Rmd).

Please [email me](mailto:mdanna2@gmu.edu) with any questions.
