---
title: "CRIM 515 Project Template"
author: "Your Name"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  cleanrmd::html_document_clean:
    theme: water-dark
    toc: yes
---

Each research project will follow the general flow outlined below. Use this format as much or as little as you'd like, as long as the required components are covered.

# Research QuestionN

### INSTRUCTIONS

# Literature Review

### INSTRUCTIONS

# Data

### INSTRUCTIONS

# Methods

### INSTRUCTIONS

# Findings

### INSTRUCTIONS

# So What

### INSTRUCTIONS

In the context of operating in a real criminal justice organization, how do your findings ***inform*** decision-making processes? Does what you’ve discovered ***confirm/deny*** conventional wisdom? How does a criminal justice organization ***operationalize*** these findings? Why do your findings matter, and what does a successful ***integration*** of your work look like? Be bold, and be specific. For example, check out [this](https://www.start.umd.edu/pubs/UIC_MPAC_START_SafeSpaces_CommunityBasedOrganizations_June2019.pdf), [this](https://start.umd.edu/pubs/UIC_MPAC_START_SafeSpaces_PublicHealthFramework_June2019.pdf), and [this](https://cebcp.org/evidence-based-policing/what-works-in-policing/research-evidence-review/focused-deterrence/). Sure, they are violent extremism, but the way they were built can be really useful in this context, too.  

As an example, specific to this project, [consider something like this](https://www.thetrace.org/2024/03/new-york-mass-shooting-victims-survivors/).

# Writing Tips

Related, some general notes about writing. Welcome to grad school, where the quality of your writing is held to a higher standard. Write directly. Thus, avoid using these words and phrases:

* Simply. Very. Indeed. Specifically. Perhaps. Arguably. Usually. Essentially. Could possibly. Could potentially. Necessarily. Only. Especially. In order to. Likely. Primarily. Generally. It is important that. It is essential to note.

Also, words have meanings. [Some are stronger than others](https://www.themuse.com/advice/185-powerful-verbs-that-will-make-your-resume-awesome). [Others aren’t real](https://www.rd.com/article/words-that-arent-words/).

Further, here’s some other strategies to consider:

* Read sentences aloud… but don’t write like you speak.
* Ask yourself - does this sentence make sense, by itself.
* It’s ok to occasionally use quotes, don’t copy specific language or words.
* If you don’t know the meaning of a word, don’t use it!

And finally, [this is just fun](https://www.thisworddoesnotexist.com/).

# Other Information/Reminders

1. When submitting your projects, you are submitting either an **HTML** or **PDF** output of your Markdown file, as an upload to Canvas - not via email.
2. When you are ready to see what the output looks like, **click the 'Knit' button.** The output file will be saved to the same folder this script is saved to.
3. *Never ever ever include any install.packages functions.* Either comment them out with a #, or delete them.
